### ISSUE TITLE
rdevice should accept a function instead of the name of a function

### ISSUE THREAD

**Issue by thomasp85** [coolbutuseless/devout#4]
Is there a reason why you currently have to pass in the function by name, rather than passing in the function directly? Current setup requires the callback function to be exported, which is often not an obvious good thing

**Comment by coolbutuseless** [comment]
I recall our discussion on this last year.

The way devout works is to pass a function to R, that gets passed to Rcpp and then called from with the Rcpp world.

The solution I came up with was to pass the name, and have have Rcpp lookup the function by name and then call it.

I feel it should be possible to pass a function as an R object, have Rcpp cast this object as a function and then call it, but I never got there during initial development.

**Comment by thomasp85** [comment]
If you have trouble let me know and I can make a PR

**Comment by coolbutuseless** [comment]
Fixed in https://github.com/coolbutuseless/devout/commit/409608d4fd2b20fd5becfc54450c6d369ff40e36

The object passed to `rdevice()` can now be any SEXP object, and its actually class/value is ignored within the Rcpp code.

The value is checked when back in the R world (`rcallback()`) and while actual function objects are now supported, I'm keeping support for "character names of functions" for a while to retrain compatibility with `devoutsvg`, `devoutpdf` etc until they're updated.
